version: "3.9"

services:

  postgredb:
    image: postgres:15-alpine
    container_name: postgredb
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: shop_db
    volumes:
      - postgres_shop_db:/var/lib/postgres

  api:
    image: sofiyatkachenia/clevertec_test_task:1.0.0
    container_name: api
    ports:
      - "8089:8088"
    depends_on:
      postgredb:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: prod
      POSTGRES_URL: jdbc:postgresql://postgredb:5432/shop_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root

volumes:
  postgres_shop_db:



