spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5433/shop_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:root}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true